
copy_dir: "D:/deploy/build"
worklist_file: "./config/worklist.txt"
summary_file: "./logs/summary.log"
#is_orin_log: true
is_orin_log: false

repositories:
  - name: "SpringMVC-MyBatis-Demo"
    execute: true
#    execute: false
    root: "D:/workspace/java/SpringMVC-MyBatis-Demo"
    path: "out/artifacts/SpringDemo_war_exploded"
    svr_path:
      - "dev/a"
      - "prd/b"
    trans_path:
      - ["src/main/java", "WEB-INF/classes"]
      - ["src/main/resources", "WEB-INF/classes"]
      - ["src/main/webapp", ""]
    trans_file:
      - [".java", ".class"]

tree_list:
  - "D:/deploy/build/SpringMVC-MyBatis-Demo"
