
copy_dir: "D:/deploy/build"
worklist_file: "./config/worklist.txt"
#is_orin_log: true
is_orin_log: false

repositories:
  - name: "SpringMVC-MyBatis-Demo"
    execute: true
#    execute: false
    dir: "a/b/c"
    root: "D:/workspace/java/SpringMVC-MyBatis-Demo"
    path: "out/artifacts/SpringDemo_war_exploded"
    trans_path:
      - ["src/main/java", "WEB-INF/classes"]
      - ["src/main/resources", "WEB-INF/classes"]
      - ["src/main/webapp", ""]
    trans_file:
      - [".java", ".class"]
